CREATE TABLE APLLIST
(MAKER      VARCHAR2(30),
 APLNAME    VARCHAR2(30));


INSERT INTO APLLIST VALUES ('BUICK', 'APLBUK');
INSERT INTO APLLIST VALUES ('CADILLAC', 'APLCAD');
INSERT INTO APLLIST VALUES ('CHEVY', 'APLCHE');
INSERT INTO APLLIST VALUES ('CHRYSLER', 'APLCRY');
INSERT INTO APLLIST VALUES ('FORD TRUCK', 'APLFDT');
INSERT INTO APLLIST VALUES ('FORD', 'APLFOR');
INSERT INTO APLLIST VALUES ('GMC', 'APLGMC');
INSERT INTO APLLIST VALUES ('INTERNATIONAL', 'APLINT');
INSERT INTO APLLIST VALUES ('ISUZU', 'APLISU');
INSERT INTO APLLIST VALUES ('LINCOLN', 'APLLIN');
INSERT INTO APLLIST VALUES ('MAZDA', 'APLMZD');
INSERT INTO APLLIST VALUES ('OLDSMOBILE', 'APLOLD');
INSERT INTO APLLIST VALUES ('PORSCHE', 'APLPOR');
INSERT INTO APLLIST VALUES ('RENAULT', 'APLREN');
INSERT INTO APLLIST VALUES ('SAAB', 'APLSAB');
INSERT INTO APLLIST VALUES ('SUBARU', 'APLSUB');
INSERT INTO APLLIST VALUES ('TOYOTA', 'APLTOY');
INSERT INTO APLLIST VALUES ('UPS', 'APLUPS');
INSERT INTO APLLIST VALUES ('VOLKSWAGEN', 'APLVOL');

COMMIT;
